### ISSUE TITLE
`check` error exit code when it fails

### ISSUE THREAD

**Issue by wdoug** [TimMikeladze/tsc-baseline#16]
Currently, when new errors are added that aren't included in the baseline, the `check` command continues to output a 0 (success) exit code with just a std err message about the new errors. I personally feel like it should return a non-zero exit code so that when I run this in CI it properly fails the job when new errors are added.

**Comment by TimMikeladze** [comment]
@wdoug if you send this as a PR, I'll publish a new version 👍

**Comment by wdoug** [comment]
> @wdoug if you send this as a PR, I'll publish a new version 👍

Done. Thanks!
