### ISSUE TITLE
Error if the baseline file isn't in the expected format

### ISSUE THREAD

**Issue by wdoug** [TimMikeladze/tsc-baseline#24]
With the recent change to use `count` instead of location information if someone upgrades this library but still has a baseline file from the previous version, that could result in unexpected output. In that scenario, when running `check` the CLI should probably output an error and say that the baseline needs to be regenerated.

**Comment by TimMikeladze** [comment]
Maybe a version number written into the baseline file? Then when `check` runs the version numbers can be compared and a warning printed or error code returned.
