### ISSUE TITLE
When new errors are found, the report no longer includes the line and column numbers

### ISSUE THREAD

**Issue by BrianBasor** [TimMikeladze/tsc-baseline#27]
I really like the new baseline logic that ignores line and column numbers when comparing current errors against baseline errors.  However, when new errors are displayed, they no longer include line and column numbers.

## Current output:
```
File: some/path/SomeFile.js
Message: Some TypeScript error message
Code: TSXXXX
Count of new errors: 1
Hash: blablabla
```

If I can't figure out where the error is coming from, I can always run `tsc` and grep for the filename since it reports line and column numbers, but I'd like to avoid that extra step.

When we parse the TypeScript errors, we could keep the line and column number properties around for use when reporting new errors, and still avoid using them for matching the baseline.  I could code that up next week if it sounds good to you @TimMikeladze and @wdoug .

What do you think?

**Comment by wdoug** [comment]
I'm curious how that would work if there are multiple of a certain type of error. Say there are two existing errors of type X, then when running `check` there are now 5 errors of type X. What if the file changes and none of the errors are where they were previously. Do you just output the line numbers for all 5?

**Comment by BrianBasor** [comment]
Good question.  Yes, I do think it would be useful to output the line and column numbers for all 5 in that scenario.  At that point, the developer's task is to find the locations in the code that are generating at least 3 out of 5 of those errors and fix them in order to get the results back down to two errors or fewer.  And having line and column numbers for all 5 seems like the easiest way to accomplish that.

Does that make sense to you, or do you envision a better approach?

**Comment by wdoug** [comment]
I think this sounds excellent from a developer experience perspective.
